<?php
date_default_timezone_set('PRC');
$array = ['Value1','Value2','Value3','Value4'];
$outerObj = new OuterImpl(new ArrayIterator($array));
foreach ($outerObj as $key => $value){
    echo "++".$key."-".$value."\n";
}
class OuterImpl extends IteratorIterator{
    public function current()
    {
       return  parent::current()."_tail"; // TODO: Change the autogenerated stub
    }
    public function key()
    {
        return "Pre_".parent::key(); // TODO: Change the autogenerated stub
    }
}